version: '3'

services:
  neo4j:
    image: neo4j:5.11
    container_name: affiliate-neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/T3sla12e!  # Change this!
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/import
      - neo4j_plugins:/plugins
    networks:
      - affiliate_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7474"]
      interval: 10s
      timeout: 10s
      retries: 5

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: affiliate-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=T3sla12e!  # Match with neo4j service
      - SHOPIFY_WEBHOOK_SECRET=your_shopify_webhook_secret
      - FIREBASE_API_KEY=your_firebase_api_key
      - FIREBASE_AUTH_DOMAIN=your_firebase_auth_domain
      - FIREBASE_PROJECT_ID=your_firebase_project_id
    depends_on:
      - neo4j
    networks:
      - affiliate_network

networks:
  affiliate_network:
    driver: bridge

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:

