services:
  # Neo4j Database (as a Docker service instead of managed database)
  - type: pserv
    name: neo4j-database
    env: docker
    repo: https://github.com/neo4j/docker-neo4j.git
    dockerfilePath: ./docker/standalone/Dockerfile
    plan: standard
    disk:
      name: neo4j-data
      mountPath: /data
      sizeGB: 10
    envVars:
      - key: NEO4J_AUTH
        value: neo4j/T3sla12e!  # Using your password from the docker-compose file
      - key: NEO4J_ACCEPT_LICENSE_AGREEMENT
        value: yes
      - key: NEO4J_apoc_export_file_enabled
        value: true
      - key: NEO4J_apoc_import_file_enabled
        value: true
      - key: NEO4J_apoc_import_file_use__neo4j__config
        value: true
      - key: NEO4J_dbms_memory_pagecache_size
        value: 512M
      - key: NEO4J_dbms_memory_heap_max__size
        value: 1G
    
  # Backend API
  - type: web
    name: affiliate-api
    env: node
    buildCommand: cd api && npm install && npm run build
    startCommand: cd api && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEO4J_URI
        value: bolt://neo4j-database:7687
      - key: NEO4J_USER
        value: neo4j
      - key: NEO4J_PASSWORD
        value: T3sla12e!  # Make sure this matches the password in NEO4J_AUTH above
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: SHOPIFY_WEBHOOK_SECRET
        sync: false
      - key: SHOPIFY_SHOP_NAME
        sync: false
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_PASSWORD
        sync: false
      - key: SHOPIFY_API_VERSION
        value: 2023-07
      - key: SHOPIFY_SHOP_URL
        sync: false
    
  # Frontend Next.js app
  - type: web
    name: affiliate-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          name: affiliate-api
          type: web
          property: host  # Changed from 'url' to 'host'
      - key: FIREBASE_API_KEY
        sync: false
      - key: FIREBASE_AUTH_DOMAIN
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
